### ISSUE TITLE
error when container is not cleanly shut down: "daemon is already running"

### ISSUE THREAD

**Issue by aleks-mariusz** [arc-ts/keepalived#1]
doing some HA testing, i powered down the host running docker that has this keepalived docker container running.. when the host came back up, the keepalive daemon continually complains about it already running:

```
Tue Aug  7 19:09:56 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:09:56 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:09:56 2018: daemon is already running
Tue Aug  7 19:09:57 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:09:57 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:09:57 2018: daemon is already running
Tue Aug  7 19:09:57 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:09:57 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:09:57 2018: daemon is already running
Tue Aug  7 19:09:59 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:09:59 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:09:59 2018: daemon is already running
Tue Aug  7 19:10:00 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:10:00 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:10:00 2018: daemon is already running
Tue Aug  7 19:10:02 2018: Starting Keepalived v1.3.9 (11/11,2017)
Tue Aug  7 19:10:02 2018: Opening file '/etc/keepalived/keepalived.conf'.
Tue Aug  7 19:10:02 2018: daemon is already running
```

anyway to clear this condition? or modify the dockerfile/scripts to recover from this situation ?

**Comment by mrbobbytables** [comment]
I'm not 100% sure, but if you can repeat it -- try deleting the contents of `/var/run/keepalived` to see if it clears up the issue. If it works, can set the script to clear it on startup.

**Comment by aleks-mariusz** [comment]
indeed the container has 3x pid files in /var/run/keepalived after being uncleanly brought down.  Should the init.sh clean that up when starting the container back up ?

**Comment by mrbobbytables** [comment]
Yup. I think thats the root of the problem. Should be able to quickly take care of it sometime today.

**Comment by aleks-mariusz** [comment]
might save you the trouble with this PR if it looks good to you ?

**Comment by mrbobbytables** [comment]
Merged :) Thanks!

**Comment by aleks-mariusz** [comment]
wonderful! any idea when we might see a new image on dockerhub ? 

also with the freed up time i wanted to ask about another situation i'm confused about (dunno if it's an issue or not) but i'll open a separate issue for that discussion.

**Comment by mrbobbytables** [comment]
I reopened it for now, and the image (at least latest) is already up there :)

**Comment by aleks-mariusz** [comment]
amazing, that was fast.. thanks.. opened up https://github.com/arc-ts/keepalived/issues/3 to discuss the other issue/question i had
