### ISSUE TITLE
understanding chk_kube_apiserver.sh functionality

### ISSUE THREAD

**Issue by aleks-mariusz** [arc-ts/keepalived#3]
one of the reasons i love this particular container image for keepalived (there are quite a few out there) is the promise of integrating detection of available apiserver daemon running.  

it was not something i was prepared to play with initially (as i was still getting familiar with kubernetes itself), but once i felt ready and started to look at this functionality, i couldn't get it to work properly.  i might just be misunderstanding its design, so i'm opening this issue to discuss and hopefully figure out if it is designed in a way that would fit for my use-case, or if maybe it can/should be adjusted to work for me.

so as i'm trying to lab up a k8s cluster w/ HA, i have 3 master nodes that all have the api-server running.  i bring up the first master node, and use this docker image with keepalived (along with a second nginx container to proxy across the 2 other systems also running api-server).   this docker container starts and takes the VIP and i use the VIP address to apiserver as the advertise address, and the primary/main IP (so non-loopback) address as the listen-address.

the idea that keepalived should only take/serve the VIP if the apiserver is running, is brililant.  unfortunately because of the way i have my apiserver NOT listening on localhost, [this check](https://github.com/arc-ts/keepalived/blob/babed9cde08b5e115d02adb3b94075ea85c7b8a2/skel/usr/lib/keepalived/scripts/chk_kube_apiserver.sh#L11) doesn't ever succeed with the script on my host.  and i continually see this from the container log:

```
Tue Aug  7 19:56:16 2018: /usr/lib/keepalived/scripts/chk_kube_apiserver.sh x.x.x.131 6443 exited with status 1
Tue Aug  7 19:56:19 2018: /usr/lib/keepalived/scripts/chk_kube_apiserver.sh x.x.x.131 6443 exited with status 1
Tue Aug  7 19:56:22 2018: /usr/lib/keepalived/scripts/chk_kube_apiserver.sh x.x.x.131 6443 exited with status 1
```

but I notice that on [the next line](https://github.com/arc-ts/keepalived/blob/babed9cde08b5e115d02adb3b94075ea85c7b8a2/skel/usr/lib/keepalived/scripts/chk_kube_apiserver.sh#L13), the script checks to see if the $vip is available on any interface, and the value of $vip passed into the script, in my case is the actual main IP of the node hosting the container (not the VIP), and this check fails (so it never tries the [second curl](https://github.com/arc-ts/keepalived/blob/babed9cde08b5e115d02adb3b94075ea85c7b8a2/skel/usr/lib/keepalived/scripts/chk_kube_apiserver.sh#L13))

So for example, the above log entries are from a host on x.x.x.131, and here is how i am starting the container when i have this issue:

```
docker run -d --net=host --cap-add NET_ADMIN   \
  --name k8s_api_keepalived --restart always   \
  -e KEEPALIVED_AUTOCONF=true                  \
  -e KEEPALIVED_STATE=MASTER                   \
  -e KEEPALIVED_INTERFACE=$INTERFACE           \
  -e KEEPALIVED_VIRTUAL_ROUTER_ID=2            \
  -e KEEPALIVED_UNICAST_PEER_1=x.x.x.132       \
  -e KEEPALIVED_UNICAST_PEER_2=x.x.x.133       \
  -e KEEPALIVED_KUBE_APISERVER_CHECK=true      \
  -e KUBE_APISERVER_ADDRESS=x.x.x.131          \
  -e KEEPALIVED_TRACK_INTERFACE_1=$INTERFACE   \
  -e KEEPALIVED_VIRTUAL_IPADDRESS_1="x.x.x.130/24 dev $INTERFACE" \
  arcts/keepalived
```

So could you please comment and help me figure out if/how the init.sh/chk_kube_apiserver.sh script can/should be modified to work in my use case, when the apiserver is NOT listening on localhost (and i can't have it simply bind to 0.0.0.0 as then it would also bind on the VIP), and the vip passed into the script is the main IP (and not detected in the container).

should i be passing in the .130 address as KUBE_APISERVER_ADDRESS? I would think that keepalived would not take this address until the script succeeds, which would never happen as the address isn't listed.  

i am also confused why [this check](https://github.com/arc-ts/keepalived/blob/babed9cde08b5e115d02adb3b94075ea85c7b8a2/skel/usr/lib/keepalived/scripts/chk_kube_apiserver.sh#L12) fails, since when i'm in the container and i run ip addr, it successfully sees the main IP:

```
/usr/lib/keepalived/scripts # ip addr | grep -c x.x.x.131
1
```

**Comment by mrbobbytables** [comment]
I think I know the root of the issue.

>  along with a second nginx container to proxy across the 2 other systems also running api-server

The `chk_kube_apiserver` script used in this container is for api-server failoverover _only_ and does not function correctly when attempting to also load-balance between the instances running the api-server. 

If you're looking to load-balance the connections to the api-servers you'd want to disable the check and rely on nginx itself to handle the distribution of connections and removal of down nodes. 

I will say though, at least from personal experience, the kube-apiserver can handle a pretty good amount of connections without issue. :) 

Its really just if your cluster or workload is large enough where you start needing to increase the resources to the apiserver and etcd to really handle the load that load-balancing the connections is needed.

**Comment by aleks-mariusz** [comment]
i suppose the nginx container isn't actually needed if i could always guarentee that whatever host was the master/had the VIP always had a working api-server available.  initially when i was trying to get this all working, i set the nginx up container in the case where the api-server wasn't running on the host (as just the host being up meant the keepalived container started, and the VIP got assigned but no api-server was available on that host).

i guess my next question then is, does the chk_kube_apiserver.sh script exitting unsuccessful (as is the case with my situation) mean keepalived will yield the VIP (when it lowers its priority), or does keepalived only take the VIP if the script is successful? perhaps they may sound like the same question from two different ends, but i guess i'm trying to figure out which comes first, the script needing to be successful to get the VIP or is the IP taken no matter what and then if the script is unsuccessful the VIP is released ?

I'm hoping you know off the top of your head with me having to test this myself :-)

re the part that seems misbehaving, any idea why inside the container the ```ip addr | grep $vip``` check are unsuccessful ?

```
# docker exec -it k8s_api_keepalived sh
/ # ip a s | grep -q x.x.x.131
/ # echo $?
0
/ # /usr/lib/keepalived/scripts/chk_kube_apiserver.sh x.x.x.131 6443
*** Error GET https://localhost:6443/
```

^-- doesn't seem like it ever performs the check if $vip is listed in the output of ```ip``` ?

**Comment by aleks-mariusz** [comment]
ahhh hmm, does it have to do with the fact that it's calling ```exit 1``` (inside the ```errorExit``` function), right after the localhost curl and hence the script **never** getting to [the if block](https://github.com/arc-ts/keepalived/blob/babed9cde08b5e115d02adb3b94075ea85c7b8a2/skel/usr/lib/keepalived/scripts/chk_kube_apiserver.sh#L12)? ;-)

so this i think is the reason for my issue in the first place, namely was it was designed this way on purpose (and simply the use case it was designed for doesn't match mine).. or is this a mistaken in its implementation that i happen to have been hit with.. 

is it a requirement that both curls pass (logical AND)? for my use, i need this to be a logical OR (which it currently isn't because the first failed curl exits immediately)

**Comment by mrbobbytables** [comment]
The logical AND was intended. That script itself was from the previous kubeadm guide for HA excluding the custom vip/port portion of it.

**Comment by aleks-mariusz** [comment]
any feedback on whether it can be modified to support OR instead/as well? maybe another environment variable ?

**Comment by mrbobbytables** [comment]
It shouldn't be too hard :) I'll try and get a PR out tonight.

**Comment by aleks-mariusz** [comment]
thanks, rm'ing a pid file dir is one thing, but changing this i would prefer you handle since seeing as how this is your container, it should have your guidance as to the best way to support this adjustment in behavior.  lookin forward to testing it!

**Comment by mrbobbytables** [comment]
Okay, this isn't exactly a logical OR, but I think it covers your use case -- try building off this branch
https://github.com/arc-ts/keepalived/tree/add-host-address-check

It takes an additional env variable `HOST_ADDRESS` so if you want it to check something other than localhost, just set that to the other address and it'll still check both.
