### ISSUE TITLE
Clarification for SERVICE_KEEPALIVED_CMD env variable

### ISSUE THREAD

**Issue by bsctl** [arc-ts/keepalived#5]
Please clarify the usage of `SERVICE_KEEPALIVED_CMD` env variable at row 130 of the `init.sh` script.
Thanks

**Comment by aleks-mariusz** [comment]
It looks like [this](https://github.com/arc-ts/keepalived/blob/master/skel/init.sh#L130) is an (externally-provideable) variable, which allow you a possibility to override what gets [exec'd in the init() function](https://github.com/arc-ts/keepalived/blob/master/skel/init.sh#L140), near the end of the script.

By default, the entry-point script will exec ```/usr/sbin/keepalived -n -l -f /path/to/keepalive.conf``` (adding ```-D``` if you have ```KEEPALIVED_DEBUG``` set), but if you want to override this and run ```/usr/sbin/keepalived``` with your own set of flags, that's what ```SERVICE_KEEPALIVED_CMD``` seems to be for.

**Comment by mrbobbytables** [comment]
That env variable is an artifact of the script in its previous form. It should just be `KEEPALIVED_CMD`. Will take care of that shortly.
